name: Run Fuzzy Testing

on:
  push:
    branches: [ "fuzzy-test-automation" ]
  pull_request:
    branches: [ "fuzzy-test-automation" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Start application
      run: CI=true npm run web
    - name: Wait for application to start - 2
    #Verify this line later
      run: |
        until curl --output /dev/null --silent --head --fail http://localhost:8081/health; do
          echo "Waiting for application to start..."
          sleep 10
        done
    - name: Run tests
      run: npm run test-fuzzy
    - name: Kill application
      if: always()
      run: kill $(jobs -p) || true
