name: Run Fuzzy Testing

on:
  push:
    branches: [ "fuzzy-test-automation" ]
  pull_request:
    branches: [ "fuzzy-test-automation" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Start application
      run: npm web &
    - name: Wait for application to start
      run: |
        until curl --output /dev/null --silent --head --fail http://localhost:3000/health; do
          echo "Waiting for application to start..."
          sleep 5
        done
    - name: Run tests
      run: npm test
    - name: Kill application
      if: always()
      run: kill $(jobs -p) || true
      #testing
