name: Minigame test automation

on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main
            - automated-property-testing


jobs: 
    unit_test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: npm install --legacy-peer-deps
            - run: npx jest minigame.test.js

